"""Discover which ATS a company uses by probing the public APIs with token guesses.

Usage:
    python3 scraper/sources/probe.py "Company Name" [more names...]
    python3 scraper/sources/probe.py --file data/candidates.txt --out data/companies.yaml

Candidates file format: `name | stage | hq` per line, `#` comments. Runs on GitHub
Actions (this environment's network policy blocks the ATS hosts in-session).
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from util import get_json  # noqa: E402


def token_guesses(name: str) -> list[str]:
    base = name.lower().strip()
    plain = re.sub(r"[^a-z0-9]", "", base)
    dashed = re.sub(r"[^a-z0-9]+", "-", base).strip("-")
    words = base.split()
    guesses = [plain, dashed]
    if words:
        guesses.append(words[0])
    seen, out = set(), []
    for g in guesses:
        if g and g not in seen:
            seen.add(g)
            out.append(g)
    return out


def probe(name: str) -> tuple[str, str] | None:
    """Return (ats, token) or None."""
    for tok in token_guesses(name):
        checks = [
            ("greenhouse", f"https://boards-api.greenhouse.io/v1/boards/{tok}/jobs",
             lambda d: isinstance(d, dict) and "jobs" in d),
            ("lever", f"https://api.lever.co/v0/postings/{tok}?mode=json",
             lambda d: isinstance(d, list)),
            ("ashby", f"https://api.ashbyhq.com/posting-api/job-board/{tok}",
             lambda d: isinstance(d, dict) and "jobs" in d),
            ("workable", f"https://apply.workable.com/api/v1/widget/accounts/{tok}",
             lambda d: isinstance(d, dict) and "jobs" in d),
            ("smartrecruiters", f"https://api.smartrecruiters.com/v1/companies/{tok}/postings?limit=1",
             lambda d: isinstance(d, dict) and "content" in d),
        ]
        for ats, url, ok in checks:
            data = get_json(url, min_gap=0.3)
            if data is not None and ok(data):
                return ats, tok
    return None


def probe_file(path: str, out: str):
    found, missed = [], []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, stage, hq = [x.strip() for x in line.split("|")]
        hit = probe(name)
        if hit:
            found.append((name, *hit, stage, hq))
            print(f"HIT  {name}: {hit[0]}/{hit[1]}", flush=True)
        else:
            missed.append(name)
            print(f"miss {name}", flush=True)

    lines = ["# ATS watchlist — generated by probe.py; grows weekly. Edit freely.",
             "companies:"]
    for name, ats, tok, stage, hq in found:
        lines += [f"  - name: {name}", f"    ats: {ats}", f"    token: {tok}",
                  f"    stage: {stage}", f"    hq: {hq}"]
    if missed:
        lines += ["", "# No public ATS board found (likely Darwinbox/Keka/custom — covered",
                  "# via LinkedIn guest + aggregators instead):"]
        lines += [f"#   {m}" for m in missed]
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"\n{len(found)} found, {len(missed)} missed → {out}")


if __name__ == "__main__":
    if len(sys.argv) > 2 and sys.argv[1] == "--file":
        out = sys.argv[4] if len(sys.argv) > 4 and sys.argv[3] == "--out" else "data/companies.yaml"
        probe_file(sys.argv[2], out)
    else:
        for name in sys.argv[1:]:
            hit = probe(name)
            if hit:
                print(f"  - name: {name}\n    ats: {hit[0]}\n    token: {hit[1]}")
            else:
                print(f"  # {name}: no public ATS board found")
