"""Discover which ATS a company uses by probing the public APIs with token guesses.

Usage:
    python3 scraper/sources/probe.py "Company Name" [more names...]
    python3 scraper/sources/probe.py --file data/candidates.txt --out data/companies.yaml

Candidates file format: `name | stage | hq` per line, `#` comments. Runs on GitHub
Actions (this environment's network policy blocks the ATS hosts in-session).
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from util import get_json  # noqa: E402


def token_guesses(name: str) -> list[str]:
    base = name.lower().strip()
    plain = re.sub(r"[^a-z0-9]", "", base)
    dashed = re.sub(r"[^a-z0-9]+", "-", base).strip("-")
    words = base.split()
    guesses = [plain, dashed]
    if words:
        guesses.append(words[0])
    seen, out = set(), []
    for g in guesses:
        if g and g not in seen:
            seen.add(g)
            out.append(g)
    return out


def _names_match(candidate: str, board_name: str) -> bool:
    import difflib
    a = re.sub(r"[^a-z0-9]", "", candidate.lower())
    b = re.sub(r"[^a-z0-9]", "", (board_name or "").lower())
    if not a or not b:
        return False
    return a in b or b in a or difflib.SequenceMatcher(None, a, b).ratio() >= 0.75


def _board_identity(ats: str, tok: str, data) -> str | None:
    """Best-effort canonical company name behind a board; None = API offers none."""
    if ats == "workable":
        return data.get("name")
    if ats == "greenhouse":
        board = get_json(f"https://boards-api.greenhouse.io/v1/boards/{tok}", min_gap=0.3)
        return (board or {}).get("name")
    if ats == "smartrecruiters":
        content = data.get("content") or []
        name = (content[0].get("company") or {}).get("name") if content else None
        return name or "?unverifiable?"  # never accept an SR board we can't identify
    if ats == "ashby":
        return data.get("organizationName") or data.get("name")
    return None  # lever exposes no account name


def probe(name: str) -> tuple[str, str] | None:
    """Return (ats, token) or None. A hit must pass identity verification when the
    API exposes a company name — guessed tokens collide with unrelated companies."""
    for tok in token_guesses(name):
        checks = [
            ("greenhouse", f"https://boards-api.greenhouse.io/v1/boards/{tok}/jobs",
             lambda d: isinstance(d, dict) and "jobs" in d),
            ("lever", f"https://api.lever.co/v0/postings/{tok}?mode=json",
             lambda d: isinstance(d, list)),
            ("ashby", f"https://api.ashbyhq.com/posting-api/job-board/{tok}",
             lambda d: isinstance(d, dict) and "jobs" in d),
            ("workable", f"https://apply.workable.com/api/v1/widget/accounts/{tok}",
             lambda d: isinstance(d, dict) and "jobs" in d),
            # SR answers 200 + empty content for ANY identifier — a hit needs real postings
            ("smartrecruiters", f"https://api.smartrecruiters.com/v1/companies/{tok}/postings?limit=1",
             lambda d: isinstance(d, dict) and bool(d.get("content"))),
        ]
        for ats, url, ok in checks:
            data = get_json(url, min_gap=0.3)
            if data is None or not ok(data):
                continue
            identity = _board_identity(ats, tok, data)
            if identity is not None and not _names_match(name, identity):
                print(f"     reject {ats}/{tok}: board says '{identity}'", flush=True)
                continue
            if identity is None and ats == "lever" and not data:
                continue  # empty lever board, unverifiable — too weak to keep
            return ats, tok
    return None


def probe_file(path: str, out: str):
    found, missed = [], []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, stage, hq = [x.strip() for x in line.split("|")]
        hit = probe(name)
        if hit:
            found.append((name, *hit, stage, hq))
            print(f"HIT  {name}: {hit[0]}/{hit[1]}", flush=True)
        else:
            missed.append(name)
            print(f"miss {name}", flush=True)

    lines = ["# ATS watchlist — generated by probe.py; grows weekly. Edit freely.",
             "companies:"]
    for name, ats, tok, stage, hq in found:
        lines += [f"  - name: {name}", f"    ats: {ats}", f"    token: {tok}",
                  f"    stage: {stage}", f"    hq: {hq}"]
    if missed:
        lines += ["", "# No public ATS board found (likely Darwinbox/Keka/custom — covered",
                  "# via LinkedIn guest + aggregators instead):"]
        lines += [f"#   {m}" for m in missed]
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"\n{len(found)} found, {len(missed)} missed → {out}")


if __name__ == "__main__":
    if len(sys.argv) > 2 and sys.argv[1] == "--file":
        out = sys.argv[4] if len(sys.argv) > 4 and sys.argv[3] == "--out" else "data/companies.yaml"
        probe_file(sys.argv[2], out)
    else:
        for name in sys.argv[1:]:
            hit = probe(name)
            if hit:
                print(f"  - name: {name}\n    ats: {hit[0]}\n    token: {hit[1]}")
            else:
                print(f"  # {name}: no public ATS board found")
